import 'package:apache_notice/src/notice.dart';
import 'package:test/test.dart';

void main() {
  group('generateNotice', () {
    test(
      'carries the upstream copyright line right after the first paragraph',
      () {
        final result = generateNotice(
          attribution: 'Bdaya-Dev',
          forkPointSha: 'deadbeef',
          modifiedPaths: const [],
          removedPaths: const [],
        );
        final lines = result.split('\n');
        final firstParaIndex = lines.indexWhere(
          (l) => l.contains('This product includes software developed'),
        );
        expect(firstParaIndex, greaterThanOrEqualTo(0));
        // Blank line, then the copyright line, exactly as it appears in
        // LICENSE (line 189): "Copyright 2021 LeanCode Sp. z o.o."
        expect(lines[firstParaIndex + 1], '');
        expect(lines[firstParaIndex + 2], 'Copyright 2021 LeanCode Sp. z o.o.');
      },
    );

    test('moves the regenerate-command trailer into an HTML comment so the '
        'file reads purely as attribution', () {
      final result = generateNotice(
        attribution: 'Bdaya-Dev',
        forkPointSha: 'deadbeef',
        modifiedPaths: const [],
        removedPaths: const [],
      );
      expect(result, contains('<!--'));
      expect(result, contains('-->'));
      expect(result, contains('To regenerate this file, run:'));

      // The trailer text must sit strictly between the comment markers.
      final openIdx = result.indexOf('<!--');
      final closeIdx = result.indexOf('-->');
      final regenIdx = result.indexOf('To regenerate this file, run:');
      expect(openIdx, lessThan(regenIdx));
      expect(regenIdx, lessThan(closeIdx));
    });

    test('is deterministic across repeated calls with the same input', () {
      String render() => generateNotice(
        attribution: 'Bdaya-Dev',
        forkPointSha: 'deadbeef',
        modifiedPaths: const ['b.dart', 'a.dart'],
        removedPaths: const ['z.json'],
      );
      expect(render(), render());
    });

    test(
      'labels Flutter-regenerated files as listed-only, not "cannot carry"',
      () {
        final result = generateNotice(
          attribution: 'Bdaya-Dev',
          forkPointSha: 'deadbeef',
          modifiedPaths: const [
            'dev/e2e_app/macos/Flutter/GeneratedPluginRegistrant.swift',
            'lib/a.dart',
          ],
          removedPaths: const [],
        );
        expect(
          result,
          contains(
            '- dev/e2e_app/macos/Flutter/GeneratedPluginRegistrant.swift '
            '(regenerated by Flutter tooling — listed here)',
          ),
        );
        expect(result, contains('- lib/a.dart (notice in file)'));
      },
    );
  });

  group('noticeUpToDate', () {
    test('treats a CRLF checkout of the generated text as up to date', () {
      const expected = '# NOTICE\n\nline\n';
      expect(noticeUpToDate('# NOTICE\r\n\r\nline\r\n', expected), isTrue);
    });

    test('is exact apart from line endings', () {
      const expected = '# NOTICE\n\nline\n';
      expect(noticeUpToDate('# NOTICE\n\nline\n', expected), isTrue);
      expect(noticeUpToDate('# NOTICE\n\nline changed\n', expected), isFalse);
      expect(noticeUpToDate('# NOTICE\n\nline', expected), isFalse);
    });
  });
}
