#!/usr/bin/env bash
# Modified by Bdaya-Dev from the original LeanCode Patrol source (Apache-2.0). See NOTICE.md.
set -euo pipefail

# gen_from_schema generates classes from schema.dart for every used language
# (Dart, Swift, Kotlin/Java) in the appropriate directory.

cd "$(dirname "$0")" || exit

schema="./schema.dart"
patrol_package="./packages/patrol_plus"
patrol_dart_out_dir="lib/src/platform/contracts"
patrol_dart_web_out_dir="lib/src/platform/web"

darwin_out="$patrol_package/darwin/Classes/AutomatorServer"
dart_out="$patrol_package/$patrol_dart_out_dir"

android_out="$patrol_package/android/src/main/kotlin/pl/leancode/patrol/contracts"
android_package="pl.leancode.patrol.contracts"

dart run packages/patrol_gen_plus/bin/main.dart "$schema" "$dart_out" "$darwin_out" "$android_out" "$android_package"

pushd "${patrol_package}"

dart fix --apply "$patrol_dart_out_dir"
dart format "$patrol_dart_out_dir"

dart run build_runner build --delete-conflicting-outputs --build-filter="$patrol_dart_out_dir/contracts.g.dart" --build-filter="$patrol_dart_web_out_dir/*.g.dart"

popd
