# Modified by Bdaya-Dev from the original LeanCode Patrol source (Apache-2.0). See NOTICE.md.
include: package:leancode_lint/analysis_options_package.yaml

analyzer:
  exclude:
    - build/**
  plugins:
    - custom_lint
