name: Publish to pub.dev

on:
  push:
    tags:
      - '*-v[0-9]+.[0-9]+.[0-9]+*'

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - uses: subosito/flutter-action@v2
        with:
          channel: stable

      - uses: bluefireteam/melos-action@v3
        with:
          publish: true
          create-release: true
